<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<!-- or linux-x64, etc. -->
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<StartupObject>ShGame.Net.Server.ServerMain</StartupObject>
		<PackAsTool>True</PackAsTool>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<NoWin32Manifest>true</NoWin32Manifest>
	</PropertyGroup>

	  <ItemGroup>
		  <ProjectReference Include="..\ShGame.Net\ShGame.Net.csproj" />
	  </ItemGroup>
	<ItemGroup>
		<Reference Include="..\libs\Simplelogging.dll" />
	</ItemGroup>
</Project>
