<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ShGame.Math\ShGame.Math.csproj" />
		<ProjectReference Include="..\ShGame.Util\ShGame.Util.csproj" />
	</ItemGroup>

</Project>
