<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\ShGame.Game\ShGame.Game.csproj" />
	  <ProjectReference Include="..\ShGame.Net.Shared\ShGame.Net.Shared.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Reference Include="..\libs\Simplelogging.dll" />
	</ItemGroup>

</Project>
