<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ShGame.Drawing\ShGame.Drawing.csproj" />
		<ProjectReference Include="..\ShGame.Math\ShGame.Math.csproj" />
		<ProjectReference Include="..\ShGame.Util\ShGame.Util.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Reference Include="SimpleLogging">
			<HintPath>..\libs\Simplelogging.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Services\" />
	</ItemGroup>

</Project>
